Repository 1024pix/pix4pix, pull requests merged in 2023-07, with the labels that each got.

#1 [FEATURE] Rendre configurable le référentiel coeur
  api/db/seeds/data/certification/tooling.js
  api/lib/config.js
  api/lib/domain/constants.js
  api/lib/domain/services/certification-challenges-service.js
  api/lib/infrastructure/repositories/competence-repository.js
  api/sample.env
  api/tests/acceptance/application/answers/answer-controller-save_test.js
  api/tests/acceptance/application/frameworks/frameworks-controller_test.js
  api/tests/acceptance/application/scorecards/scorecard-controller_test.js
  api/tests/acceptance/application/target-profiles/index_test.js
  api/tests/acceptance/application/users/users-controller-get-user-profile-for-admin_test.js
  api/tests/acceptance/application/users/users-controller-get-user-profile_test.js
  api/tests/acceptance/application/users/users-controller-is-certifiable_test.js
  api/tests/acceptance/application/users/users-controller-reset-scorecard_test.js
  api/tests/acceptance/application/users/users-get-shared-profile-for-campaign_test.js
  api/tests/integration/domain/services/pick-certification-challenge_test.js
  api/tests/integration/domain/usecases/get-campaign_test.js
  api/tests/integration/domain/usecases/start-writing-campaign-assessment-results-to-stream_test.js
  api/tests/integration/domain/usecases/start-writing-campaign-profiles-collection-results-to-stream_test.js
  api/tests/integration/infrastructure/repositories/area-repository_test.js
  api/tests/integration/infrastructure/repositories/campaign-assessment-participation-result-repository_test.js
  api/tests/integration/infrastructure/repositories/campaign-profile-repository_test.js
  api/tests/integration/infrastructure/repositories/campaign-profiles-collection-participation-summary-repository_test.js
  api/tests/integration/infrastructure/repositories/certified-profile-repository_test.js
  api/tests/integration/infrastructure/repositories/competence-repository_test.js
  api/tests/integration/infrastructure/repositories/learning-content-repository_test.js
  api/tests/integration/infrastructure/repositories/participant-results-shared-repository_test.js
  api/tests/integration/infrastructure/repositories/target-profile-for-admin-repository_test.js
  api/tests/integration/scripts/prod/compute-participation-results_test.js
  api/tests/tooling/domain-builder/factory/build-competence.js
  api/tests/tooling/learning-content-builder/build-learning-content.js
  api/tests/tooling/learning-content-builder/build-learning-content_test.js
  api/tests/unit/application/certification-courses/certification-course-controller_test.js
  api/tests/unit/domain/services/certification-challenges-service_test.js
  api/tests/unit/infrastructure/serializers/jsonapi/certified-profile-serializer_test.js
Labels: :rocket: Ready to Merge, Tech Review OK, cross-team

#2 [FEATURE] Amélioration de la page de connexion de Pix Admin
  admin/app/components/login-form.hbs
  admin/app/components/login-form.js
  admin/app/styles/login.scss
  admin/app/templates/login.hbs
  admin/public/platform-logo.png
Labels: :rocket: Ready to Merge, cross-team

#4 [FEATURE] Utiliser dans PixAdmin le référentiel coeur configuré
  admin/app/components/common/tubes-selection.js
  admin/app/models/framework.js
  admin/mirage/helpers/create-learning-content.js
  admin/tests/acceptance/authenticated/target-profiles/list_test.js
  admin/tests/acceptance/authenticated/target-profiles/target-profile/creation_test.js
  admin/tests/integration/components/common/tubes-selection_test.js
  admin/tests/integration/components/target-profiles/create-target-profile-form_test.js
  admin/tests/unit/components/common/tubes-selection_test.js
  api/lib/config.js
  api/lib/domain/models/Framework.js
  api/lib/infrastructure/serializers/jsonapi/framework-serializer.js
  api/tests/acceptance/application/frameworks/frameworks-controller_test.js
  api/tests/unit/infrastructure/serializers/jsonapi/framework-serializer_test.js
Labels: :rocket: Ready to Merge, Tech Review OK, cross-team

#5 [FEATURE] Utiliser l'adresse d'expédition précisée dans Brevo
  api/lib/domain/services/mail-service.js
  api/lib/infrastructure/mailers/SendinblueProvider.js
  api/tests/unit/domain/services/mail-service_test.js
  api/tests/unit/infrastructure/mailers/SendinblueProvider_test.js
Labels: :rocket: Ready to Merge

#7 Renseigner la plateforme Pix4Pix dans les emails (création de compte et changement de mot de passe)
  api/tests/unit/domain/services/mail-service_test.js
  api/translations/en.json
  api/translations/fr.json
Labels: :rocket: Ready to Merge

#6 Ne plus avoir le nombre de compétence en dur sur la page profile
  high-level-tests/e2e/cypress/support/step_definitions/login-logout.js
  mon-pix/app/components/profile-content.hbs
  mon-pix/app/models/profile.js
  mon-pix/tests/unit/models/profile_test.js
  mon-pix/translations/en.json
  mon-pix/translations/fr.json
Labels: :rocket: Ready to Merge

#8 [FEATURE] Ajouter l'authentication SSO Google
  api/db/migrations/20230711160800_add-google-identity-provider-to-authentication-methods-table.js
  api/lib/config.js
  api/lib/domain/constants/oidc-identity-providers.js
  api/lib/domain/services/authentication/GoogleOidcAuthenticationService.js
  api/lib/domain/services/authentication/authentication-service-registry.js
  api/sample.env
  api/tests/integration/domain/services/authentication/GoogleOidcAuthenticationService_test.js
  api/tests/unit/domain/services/authentication/authentication-service-registry_test.js
  mon-pix/app/components/signin-form.hbs
  mon-pix/app/styles/pages/_sign-form.scss
  mon-pix/public/images/logo/google-logo.svg
  mon-pix/translations/en.json
  mon-pix/translations/fr.json
Labels: :rocket: Ready to Merge, Tech Review OK, cross-team

#10 [FEATURE] Changement du logo pour le Pix4Pix App
  mon-pix/app/components/campaign-start-block.hbs
  mon-pix/app/components/footer.hbs
  mon-pix/app/components/inaccessible-campaign.hbs
  mon-pix/app/components/password-reset-demand-form.hbs
  mon-pix/app/components/pix-logo.hbs
  mon-pix/app/components/reset-password-form.hbs
  mon-pix/app/components/routes/login-or-register.hbs
  mon-pix/app/components/signin-form.hbs
  mon-pix/app/components/signup-form.hbs
  mon-pix/app/components/update-expired-password-form.hbs
  mon-pix/app/styles/components/_pix-logo.scss
  mon-pix/app/templates/authentication/login-or-register-oidc.hbs
  mon-pix/app/templates/not-connected.hbs
  mon-pix/app/templates/terms-of-service.hbs
  mon-pix/public/images/platform-logo.png
  mon-pix/tests/integration/components/challenge-statement_test.js
  mon-pix/tests/integration/components/comparison-window_test.js
  mon-pix/tests/integration/components/footer_test.js
  mon-pix/tests/integration/components/pix-logo_test.js
  mon-pix/tests/integration/components/routes/campaigns/invited/fill-in-participant-external-id_test.js
Labels: :rocket: Ready to Merge, cross-team
